name = "xugou-app"
main = "backend/src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

minify = true # 生产环境压缩代码

# 设置自定义域名
routes = [
  { pattern = "xugou.mdzz.uk", custom_domain = true }
]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou_db"
database_id = "32a2ca5f-3a77-4b08-965e-804612557880"

[assets]
binding = "ASSETS"
directory = "frontend/dist"
not_found_handling = "single-page-application"

[version_metadata]
binding = "CF_VERSION_METADATA"